<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Company>VisaryPDF</Company>
    <Product>VisaryPDF</Product>
    <Version>1.0.0</Version>
    <!-- Pinned PDFium build from https://github.com/bblanchon/pdfium-binaries -->
    <PdfiumRelease>chromium/8066</PdfiumRelease>
  </PropertyGroup>
</Project>
